# -*- coding: utf-8 -*-
"""qr_nlp7_geo_ENG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kg4COkxHwdJ0JOuAwpnyYivFN55jgHzh
"""

# ==========================================
# 0. SUDAH PENGUMUMAN MedisAI Pro: Versi Terintegrasi (Password + Geofencing + Full Data) - TRANSLATE
# ==========================================
import streamlit as st
import pandas as pd
import qrcode
import time
import os
from io import BytesIO
from geopy.distance import geodesic
from datetime import datetime

# ==========================================
# 1. INITIALIZATION & DATABASE
# ==========================================
st.set_page_config(page_title="MedisAI Pro: Full Integrated CDSS", layout="wide")

DATA_FILE = "medical_registry_v3.csv"
MASTER_PASSWORD = "access123"

# Struktur Data Lengkap sesuai permintaan awal
DATA_STRUCTURE = [
    "User_ID", "BPJS_ID", "Name", "Birth_Date", "Gender",
    "Blood_Type", "Weight_kg", "Height_cm", "Chronic_Diseases",
    "Current_Medication", "Allergies", "Emergency_Contact_Name",
    "Emergency_Contact_Phone", "Medical_History", "Last_Update"
]

if not os.path.exists(DATA_FILE):
    df_init = pd.DataFrame(columns=DATA_STRUCTURE)
    df_init.to_csv(DATA_FILE, index=False)

HOSPITALS = [
    {"name": "RSUP Dr. Sardjito", "lat": -7.7684, "lon": 110.3737},
    {"name": "RS JIH Yogyakarta", "lat": -7.7569, "lon": 110.4021},
    {"name": "RSA UGM", "lat": -7.7423, "lon": 110.3492},
]

# ==========================================
# 2. CORE ENGINES (NEWS2)
# ==========================================

def calculate_news2(rr, spo2, bps, hr, avpu):
    score = 0
    if rr <= 8 or rr >= 25: score += 3
    elif 21 <= rr <= 24: score += 2
    if spo2 <= 91: score += 3
    elif 92 <= spo2 <= 93: score += 2
    if bps <= 90 or bps >= 220: score += 3
    elif 91 <= bps <= 100: score += 2
    if hr <= 40 or hr >= 131: score += 3
    elif 111 <= hr <= 130: score += 2
    if avpu != "Alert": score += 3

    if score >= 7: return score, "RED (CRITICAL)", "#d32f2f"
    elif score >= 5: return score, "ORANGE (URGENT)", "#f57c00"
    return score, "GREEN (STABLE)", "#388e3c"

# ==========================================
# 3. MAIN INTERFACE
# ==========================================
tab_reg, tab_admin, tab_emergency = st.tabs([
    "🆕 1. Registration & QR",
    "🔐 2. Database (Admin)",
    "🚑 3. Emergency Mode (CDSS)"
])

# ------------------------------------------
# TAB 1: REGISTRASI (INPUT DATA LENGKAP)
# ------------------------------------------
with tab_reg:
    st.subheader("Add Patient")
    with st.form("reg_form", clear_on_submit=True):
        c1, c2 = st.columns(2)
        d = {}
        with c1:
            d["User_ID"] = st.text_input("User ID")
            d["BPJS_ID"] = st.text_input("BPJS_ID")
            d["Name"] = st.text_input("Name")
            d["Birth_Date"] = st.date_input("Birth_Date")
            d["Gender"] = st.selectbox("Gender", ["Male", "Female"])
            d["Blood_Type"] = st.selectbox("Blood_Type", ["A", "B", "AB", "O"])
            d["Weight_kg"] = st.number_input("Weight (kg)", 0, 200)
            d["Height_cm"] = st.number_input("Height (cm)", 0, 250)
        with c2:
            d["Emergency_Contact_Name"] = st.text_input("Emergency_Contact_Name")
            d["Emergency_Contact_Phone"] = st.text_input("Emergency_Contact_Phone")
            d["Current_Medication"] = st.text_input("Current_Medication")
            d["Chronic_Diseases"] = st.text_area("Chronic_Diseases")
            d["Allergies"] = st.text_area("Allergies")
            d["Medical_History"] = st.text_area("Medical_History (Privat)")
            d["Last_Update"] = datetime.now().strftime("%Y-%m-%d")

        if st.form_submit_button("Save & Generate QR"):
            if d["User_ID"] and d["Name"]:
                df = pd.read_csv(DATA_FILE)
                df = pd.concat([df, pd.DataFrame([d])], ignore_index=True)
                df.to_csv(DATA_FILE, index=False)

                st.success(f"Patient {d['Name']} was successfully registered!")
                qr_url = f"http://localhost:8501/?uid={d['User_ID']}"
                img = qrcode.make(qr_url)
                buf = BytesIO(); img.save(buf, format="PNG")
                #st.image(buf.getvalue(), caption=f"QR Code Patien: {d['User_ID']}")
                st.image(buf.getvalue(), caption=f"http://localhost:8501/?uid= {d['User_ID']}")
            else:
                st.error("ID and Name required!")

# ------------------------------------------
# TAB 2: DATABASE ADMIN (MASTER PASSWORD)
# ------------------------------------------
with tab_admin:
    st.subheader("🔐 Database Management")
    pwd = st.text_input("Input Master Password for accessing database:", type="password")

    if pwd == MASTER_PASSWORD:
        st.success("Access granted")
        df_all = pd.read_csv(DATA_FILE)
        st.dataframe(df_all, use_container_width=True)

        st.divider()
        st.subheader("📝 Edit Patient")
        edit_uid = st.selectbox("Select Patient ID to edit:", df_all["User_ID"].unique())

        if edit_uid:
            p_old = df_all[df_all["User_ID"] == edit_uid].iloc[0]
            with st.form("edit_form"):
                e_name = st.text_input("Name", value=p_old["Name"])
                e_chronic = st.text_area("Chronic Diseases", value=p_old["Chronic_Diseases"])
                e_allergies = st.text_area("Allergies", value=p_old["Allergies"])
                e_history = st.text_area("Medical History", value=p_old["Medical_History"])

                if st.form_submit_button("Update Data"):
                    df_all = df_all[df_all["User_ID"] != edit_uid]
                    p_old["Name"] = e_name
                    p_old["Chronic_Diseases"] = e_chronic
                    p_old["Allergies"] = e_allergies
                    p_old["Medical_History"] = e_history
                    p_old["Last_Update"] = datetime.now().strftime("%Y-%m-%d")

                    df_all = pd.concat([df_all, pd.DataFrame([p_old])], ignore_index=True)
                    df_all.to_csv(DATA_FILE, index=False)
                    st.success("Data Updated Successfully!")
                    st.rerun()
    elif pwd != "":
        st.error("Wrong Password!")

# ------------------------------------------
# TAB 3: MODE DARURAT (CDSS & GEOFENCING)
# ------------------------------------------
with tab_emergency:
    scanned_uid = st.query_params.get("uid")
    c_left, c_right = st.columns([1, 2])

    with c_left:
        st.subheader("🔍 Emergency Information")
        if scanned_uid:
            df_em = pd.read_csv(DATA_FILE)
            patient = df_em[df_em["User_ID"].astype(str) == str(scanned_uid)]

            if not patient.empty:
                p = patient.iloc[0]
                # Menampilkan data publik darurat
                st.markdown(f"""
                <div style="background:#fff; padding:15px; border-radius:10px; border-left:5px solid red; color:black; border: 1px solid #ddd;">
                    <h3 style="margin:0;">{p['Name']}</h3>
                    <p><b>Gol. Darah:</b> {p['Blood_Type']} | <b>BPJS:</b> {p['BPJS_ID']}</p>
                    <hr>
                    <p style="color:red;"><b>⚠️ ALERGI:</b> {p['Allergies']}</p>
                    <p><b>Kronis:</b> {p['Chronic_Diseases']}</p>
                    <p><b>Kontak Darurat:</b> {p['Emergency_Contact_Name']} ({p['Emergency_Contact_Phone']})</p>
                </div>
                """, unsafe_allow_html=True)

                # Fitur Master Password untuk melihat Riwayat Medis Privat di Mode Darurat
                with st.expander("🔓 View Complete Medical History (Password Required)"):
                    em_pwd = st.text_input("Medical Password:", type="password", key="em_pwd")
                    if em_pwd == MASTER_PASSWORD:
                        st.info(f"**Private Medical History:**\n{p['Medical_History']}")
                    elif em_pwd != "":
                        st.error("Access denied")
            else:
                st.error("Patient ID not found.")
        else:
            st.info("Waiting for QR Scan or Enter UID Parameters in URL.")

        st.divider()
        st.subheader("🩺 Clinical Input (TTV)")
        v_rr = st.number_input("Breath (bpm)", 5, 50, 22)
        v_spo2 = st.number_input("SpO2 (%)", 50, 100, 93)
        v_bps = st.number_input("Sistolik BP", 50, 250, 105)
        v_hr = st.number_input("heart rate (bpm)", 20, 200, 90)
        v_avpu = st.selectbox("response rate (AVPU)", ["Alert", "Voice", "Pain", "Unresponsive"])

    with c_right:
        if st.button("RUNNING CDSS", use_container_width=True, type="primary"):
            score, level, color = calculate_news2(v_rr, v_spo2, v_bps, v_hr, v_avpu)

            st.markdown(f"""
            <div style='background:{color}; color:white; padding:20px; border-radius:10px; text-align:center;'>
                <small>TRIAGE RESULT</small>
                <h1 style='margin:0;'>{level}</h1>
                <p>NEWS2 TOTAL SCORE: {score}</p>
            </div>
            """, unsafe_allow_html=True)

            # Geofencing
            st.subheader("📍 Geofencing: Nearest Hospital")
            u_lat, u_lon = -7.7700, 110.3700 # Simulasi lokasi saat ini (Yogyakarta)
            distances = [{"name": h["name"], "dist": geodesic((u_lat, u_lon), (h["lat"], h["lon"])).km} for h in HOSPITALS]
            nearest = sorted(distances, key=lambda x: x["dist"])[0]

            c1, c2 = st.columns(2)
            c1.metric("Nearest Facilities", nearest["name"])
            c2.metric("Estimated Distance", f"{nearest['dist']:.2f} KM")

            if score >= 5:
                st.warning("⚠️ **IMMEDIATE ACTION:** The patient requires immediate medical evaluation. Use the fastest route to the nearest hospital..")

